// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Mbadog",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Mbadog",
            targets: ["AppModule"],
            bundleIdentifier: "com.Tiffany.Mbadog",
            teamIdentifier: "G8XXRLYN3L",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/twostraws/Subsonic", "0.2.0"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Subsonic", package: "subsonic")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)